spring:
  datasource:
    url: jdbc:mysql://srv.myqahxl.xin:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: mall
    password: 4rE5cnmrimKxWnJB
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: srv.myqahxl.xin # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: redis_nKhctf # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

minio:
  endpoint: http://srv.myqahxl.xin:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: QKWioQc1iok1TfndalGx #访问的key
  secretKey: rpjCxZ5mw8yuy27B5vB5Mdiu9dyjMf5ji2rW70RK #访问的秘钥

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info

logstash:
  host: logstash